### ISSUE TITLE
run with example  with version v3.0

### ISSUE THREAD

**Issue by chengxuwei** [statefulj/statefulj#23]
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.reflect.Field.getDeclaredAnnotation(Ljava/lang/Class;)Ljava/lang/annotation/Annotation;
	at org.statefulj.persistence.StateFieldAccessor.init(StateFieldAccessor.java:27)
	at org.statefulj.common.utils.FieldAccessor.<init>(FieldAccessor.java:35)
	at org.statefulj.persistence.StateFieldAccessor.<init>(StateFieldAccessor.java:22)
	at org.statefulj.persistence.memory.MemoryPersisterImpl.initStateFieldAccessor(MemoryPersisterImpl.java:157)
	at org.statefulj.persistence.memory.MemoryPersisterImpl.getStateFieldAccessor(MemoryPersisterImpl.java:150)
	at org.statefulj.persistence.memory.MemoryPersisterImpl.getCurrent(MemoryPersisterImpl.java:112)
	at org.statefulj.fsm.FSM.getCurrentState(FSM.java:200)
	at org.statefulj.fsm.FSM.onEvent(FSM.java:115)
	at com.jimi.fsm.App.main(App.java:100)

**Comment by chengxuwei** [comment]
modify State state = field.getDeclaredAnnotation(State.class);
to:  
State state = field.getAnnotation(State.class);

**Comment by supercoffee** [comment]
I also ran into this using version 3.0 on Android.  The method `getDeclaredAnnotation(Class<T> annotationClass)` was [added in Java 8](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/AccessibleObject.html#getDeclaredAnnotation-java.lang.Class-).  Usage of this method prevents the library from running at all on Java versions <8.
