### ISSUE TITLE
Problem using framework

### ISSUE THREAD

**Issue by dylaniato35** [statefulj/statefulj#7]
I'm trying to implement a simple FSM to control states of an order. So I have imported all the dependencies in my pom.xml

		<dependency>
			<groupId>org.statefulj.framework</groupId>
			<artifactId>statefulj-framework-persistence-jpa</artifactId>
			<version>${statefulj.version}</version>
		</dependency>
		<dependency>
			<groupId>org.statefulj.framework</groupId>
			<artifactId>statefulj-framework-binders-camel</artifactId>
			<version>${statefulj.version}</version>
		</dependency>
		<dependency>
			<groupId>org.statefulj.framework</groupId>
			<artifactId>statefulj-framework-binders-springmvc</artifactId>
			<version>${statefulj.version}</version>
		</dependency>
		<dependency>
			<groupId>org.statefulj.framework</groupId>
			<artifactId>statefulj-framework-binders-jersey</artifactId>
			<version>${statefulj.version}</version>
		</dependency>

Our statefulj version is 1.0.5. Following the installation guide, we have created a simple Order entity, a repository and a DAO. After that, I created a simple OrderController, which has a Camel event:

    @StatefulController(
	    clazz=Order.class,
	    startState=NON_EXISTENT
	)
    public class OrderController {
	
	OrderController() {
		System.out.println("Controller");
	}
	
	public static final String ORDER_CREATED = "camel:file:C:/";
	
	@Transition(from=NON_EXISTENT, event=ORDER_CREATED, to=READY_FOR_APPROVAL)
	public void createOrder(Order order, String event) {
		System.out.println("Order created!");
	}
    }

which simply make a print on the console. The Camel route copy a file from a location to another (and it works). 

The problem is that when I try to deploy to a Tomcat, it gives me the following exception:

org.springframework.beans.factory.BeanCreationException: Unable to create bean; nested exception is java.lang.RuntimeException: Unable to locate binder: camel
        at org.statefulj.framework.core.StatefulFactory.postProcessBeanDefinitionRegistry(StatefulFactory.java:292)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:119)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1930)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to locate binder: camel
        at org.statefulj.framework.core.StatefulFactory.buildFramework(StatefulFactory.java:486)
        at org.statefulj.framework.core.StatefulFactory.postProcessBeanDefinitionRegistry(StatefulFactory.java:282)
        ... 19 more

Seems that the problem is in the library and not in my project, can you help me?

For matter of completeness, here is my configuration file (I'm using Spring):

    <context:component-scan base-package="prova.camel" />
    <context:annotation-config />
	
    <jpa:repositories base-package="prova.camel.repo" />

    <import resource="spring-persistence.xml" />

    <camelContext xmlns="http://camel.apache.org/schema/spring">
		<route id="helloRoute">
			<from uri="file:C:/test" />
			<to uri="file:C:/testDest" />
		</route>
    </camelContext>
	
    <bean name="/StatefulJConfig" class="prova.camel.config.StatefulJConfig" />

and my StatefulJConfig bean

    @Configuration
    public class StatefulJConfig {
	@Bean
	public StatefulFactory statefulJFactory() {
		return new StatefulFactory("prova.camel");
	}
    }

thank you!

**Comment by dylaniato35** [comment]
Solved just using the empty constructor for StatefulFactory.

**Comment by developer-x** [comment]
Yes - the input to the StatefulJ factory is not for scanning for controllers - it tells StatefulJ where to find binders and persisters.  In effect, that was telling StatefulJ to look for the camel binders in the "prova.camel" package.
